### ISSUE TITLE
Wrong user on 'comment' notification

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/dashboard#17]
Looks like the user that is shown on the notification elements for 'comment' notifications is always the issue reporter:

![image](https://user-images.githubusercontent.com/13281350/50639761-e255db80-0f62-11e9-8fed-6c66a47cac92.png)

![image](https://user-images.githubusercontent.com/13281350/50639773-ee419d80-0f62-11e9-96fd-36a690a92b6f.png)

**Comment by pellebjerkestrand** [comment]
Yeah, sorry about that (`user: getUser(issue.user)` in `github.js:18`) 😅.

**Comment by asbjornh** [comment]
Just gonna leave this here to test the new repo name
