### ISSUE TITLE
Wrong user on `close` notification

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/dashboard#19]
The issue opener is used as the closer.

![close](https://user-images.githubusercontent.com/2156573/50651609-31f8cf00-0f84-11e9-9b53-98457d192efb.png)

<img width="535" alt="screen shot 2019-01-03 at 18 19 01" src="https://user-images.githubusercontent.com/2156573/50651616-3624ec80-0f84-11e9-84e3-e410db0cb92b.png">

**Comment by asbjornh** [comment]
The payloads include a `sender` property in addition to the `issue.user` that is currently used. Might be the thing we want

**Comment by asbjornh** [comment]
The only way to know if the fix works is to close an issue. Crossing fingers and closing this!

**Comment by asbjornh** [comment]
Yay!

![image](https://user-images.githubusercontent.com/13281350/50686290-070e8980-101d-11e9-81c9-60e2a48fcdc2.png)
