### ISSUE TITLE
Add volume control

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/dashboard#26]
The notification sound volume can be a bit high compared to other sounds (music etc.).

**Comment by asbjornh** [comment]
What about just setting the volume to a suitable level? :P

**Comment by pellebjerkestrand** [comment]
Sure, you can set the system volume to a suitable level, but since other things also make sounds it's the dashboard's volume relative to the system volume I want to set.

**Comment by asbjornh** [comment]
I meant setting the volume of the dashboard to a suitable level, not the system volume

**Comment by pellebjerkestrand** [comment]
We don't know what level that would be, though.

**Comment by asbjornh** [comment]
Just put on a song, play the sound a few times and set it to a level that makes you happy.

**Comment by pellebjerkestrand** [comment]
The system volume is then too low for the song to be loud enough.

**Comment by asbjornh** [comment]
What?? 😄 Your system volume is too low because you adjusted the volume of the notification sound?
