### ISSUE TITLE
Aggregated stats

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/dashboard#33]
# One PR per thing!

Would be cool to have some aggregated stats. Could be a section above the projects, or a page of its own. Here are some ideas:

- ~Combined activity graph~
- Level of activity for the current week/month/whatever compared to previous weeks (Maybe like a speedometer-looking thing)
- Number of closed issues for the past [time]
- ~Most active member of the past [time]~
- ~Most active project of the past [time]~
- ~Project with the highest number of open issues~
- ~Visualization of average activity by weekday~
- ~Visualization of average activity by hour~

**Comment by asbjornh** [comment]
Opening this again because there’s still more fun things to do here

**Comment by pellebjerkestrand** [comment]
This is how we get huge PRs, though. One issue per thing?

**Comment by asbjornh** [comment]
I fixed it
