### ISSUE TITLE
Show number of open PRs

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/Dashboard#8]
It would be nice to see the number of open PRs as well as the number of issues, so that we can focus on closing PRs before moving on to resolving issues.

**Comment by pellebjerkestrand** [comment]
It seems like the issues number is actually issues + PRs 🤔.

**Comment by asbjornh** [comment]
I think the easiest way to do so is to do increments and decrements on a database value for `open` and `close` actions on the `pull_request` event type. That does feel icky tho

**Comment by asbjornh** [comment]
> It seems like the issues number is actually issues + PRs 🤔.

Oh wow, you're right! :O 

![image](https://user-images.githubusercontent.com/13281350/50211871-fce06000-0379-11e9-9eac-bec557d84535.png)

![image](https://user-images.githubusercontent.com/13281350/50211885-05389b00-037a-11e9-8d3a-34d06660a8d6.png)

**Comment by asbjornh** [comment]
There's actually two fields in the webhook payloads: `open_issues` and `open_issues_count`. But in the payloads I've stored locally these show the same count, so I don't know if there is any useful difference.

Currently the `open_issues` field is used.

**Comment by pellebjerkestrand** [comment]
Yeah, they always have the same value.

**Comment by pellebjerkestrand** [comment]
> I think the easiest way to do so is to do increments and decrements on a database value for `open` and `close` actions on the `pull_request` event type. That does feel icky tho

IMO too icky.

**Comment by asbjornh** [comment]
So then what we'd have to do is to have a PR counter in the database and subtract the PR count from the issue count sent to the view 😛

**Comment by asbjornh** [comment]
> IMO too icky.

Yeah. Firebase does have a decent API for doing that sort of stuff though: https://github.com/Creuna-Oslo/Dashboard/blob/e38fb59842d5742245513262678e2c63a229cb46/functions/index.js#L26

**Comment by pellebjerkestrand** [comment]
Too easy to get out of sync, IMO.

**Comment by pellebjerkestrand** [comment]
😞

**Comment by pellebjerkestrand** [comment]
😭
